/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4_tache1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Felix
 */
public class AnalyticForm extends javax.swing.JPanel {

    private Connection dbConnection;
    
    /**
     * Creates new form AnalyticForm
     */
    public AnalyticForm(Connection dbConnection) {
        this.dbConnection = dbConnection;
        initComponents();
        
        Statement stmt = null;
        ResultSet rs = null;
        
        try{
            stmt = dbConnection.createStatement();
            rs = stmt.executeQuery("SELECT province FROM DIMENSION_CLIENT GROUP BY province");
            
            while(rs.next()){
                cmbProvince.addItem(rs.getNString(1));
            }
            
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }finally{
            try{
                if(stmt != null) stmt.close();
                if(rs != null) rs.close();
            } catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbAgeGroup = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbProvince = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbDayOfTheWeek = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox();
        btnQuery = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();

        jLabel1.setText("Age group:");

        cmbAgeGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95" }));

        jLabel2.setText("Province:");

        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));

        jLabel3.setText("Day of the week:");
        jLabel3.setToolTipText("");

        cmbDayOfTheWeek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Monday", "Tusesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel4.setText("Month");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        btnQuery.setText("Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        jLabel5.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDayOfTheWeek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAgeGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnQuery)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResult)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnQuery)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblResult))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        Statement stmt = null;
        ResultSet rs = null;
        String selectQuery = "SELECT COUNT(*) FROM FACT_LOCATION l JOIN DIMENSION_CLIENT c ON l.idClient = c.idClient JOIN DIMENSION_DATE d ON l.idDate = d.idDate";
        String whereClause = "";
        
        if(!cmbAgeGroup.getSelectedItem().toString().equals("All")){
            whereClause += "c.ageGroup = "+ cmbAgeGroup.getSelectedItem().toString();
        }
        
        if(!cmbProvince.getSelectedItem().toString().equals("All")){
            if(!whereClause.equals("")) whereClause += " AND ";
            whereClause += "c.province = '"+ cmbProvince.getSelectedItem().toString() +"'";
        }
        
        if(!cmbDayOfTheWeek.getSelectedItem().toString().equals("All")){
            if(!whereClause.equals("")) whereClause += " AND ";
            whereClause += "d.dayOfTheWeek = '"+ cmbDayOfTheWeek.getSelectedItem().toString() +"'";
        }
        
        if(!cmbMonth.getSelectedItem().toString().equals("All")){
            if(!whereClause.equals("")) whereClause += " AND ";
            whereClause += "d.month = '"+ cmbMonth.getSelectedItem().toString() +"'";
        }
        
        if(!whereClause.equals("")){
            selectQuery = selectQuery + " WHERE " + whereClause;
        }
        
        System.out.println(selectQuery);
        
        try{
            stmt = dbConnection.createStatement();
            rs = stmt.executeQuery(selectQuery);
            rs.next();
            lblResult.setText(rs.getInt(1) + "");
            
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }finally{
            try{
                if(stmt != null) stmt.close();
                if(rs != null) rs.close();
            } catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnQueryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuery;
    private javax.swing.JComboBox cmbAgeGroup;
    private javax.swing.JComboBox cmbDayOfTheWeek;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbProvince;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables
}
